### ISSUE TITLE
error[E0463]: can't find crate for `core`

### ISSUE THREAD

**Issue by juliangaal** [maciejhirsz/kobold#34] opened 2023-03-25 00:13 UTC
This is part of a longer error message, [gist here](https://gist.github.com/juliangaal/19cfe9e439e339120d378da5febac7ee)

My environment:

* Ubuntu 20.04
* rustc -vV
  ```
  rustc 1.68.1 (8460ca823 2023-03-20)
  binary: rustc
  commit-hash: 8460ca823e8367a30dda430efda790588b8c84d3
  commit-date: 2023-03-20
  host: x86_64-unknown-linux-gnu
  release: 1.68.1
  LLVM version: 15.0.6
  ```
* rustup show
  ```
    rustup show
  Default host: x86_64-unknown-linux-gnu
  rustup home:  /home/julian/.rustup
  
  installed targets for active toolchain
  --------------------------------------
  
  wasm32-unknown-unknown
  x86_64-unknown-linux-gnu
  
  active toolchain
  ----------------
  
  stable-x86_64-unknown-linux-gnu (default)
  rustc 1.68.1 (8460ca823 2023-03-20)
  ```

Thanks for your help

**Comment by maciejhirsz** [comment] 2023-03-25 10:35
It's curious that it's both itoa and ryu that are the issue since they are both no_std. I'm on debian-based OS myself and this all looks well configured. Might be trunk or something else is using the wrong toolchain? Maybe try to force reinstall either `trunk` or `wasm-bindgen-cli` (or both)?

```
cargo install trunk --locked --force
cargo install wasm-bindgen-cli --locked --force
```

**Comment by maciejhirsz** [comment] 2023-03-31 14:53
Haven't been able to reproduce this, and haven't seen anyone else report anything similar, so gonna close this for now as I can't see how this is not a local setup problem.

Feel free to re-open the issue if errors persist.

**Closed by maciejhirsz** 2023-03-31 14:53 UTC
